# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "kenophob.io"



author:
  name:             kenophob.io
#  facebook:         your-id
#  twitter:          your-id
  github:           kenophobio
#  linkedin:         your-id
#  medium:           your-id
#  tumblr:           your-id
#  email:            your-id@your-email.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "kenophob-io"

# URL
#url:                "https://AWEEKJ.github.io" # the base hostname & protocol for your site
url:                "http://kenophobio.github.io" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/Amsterdam
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/AWEEKJ/Kiko-plus"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
