# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "월 간 || 좀 더 빠 르 게"



author:
  name:            pocomosso
  facebook:         
  twitter:          
  github:           
  linkedin:         
  medium:           
  tumblr:           
  email:            2pocomosso@gmail.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "your-id"

# URL
#url:                "https://AWEEKJ.github.io" # the base hostname & protocol for your site
url:                "http://localhost:4000" # use this url when develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "pocomosso"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            ""



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
