# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "The O'Bartman Logs"



author:
  name:             oscar-bartman
  facebook:         your-id
  twitter:          your-id
  github:           your-id
  linkedin:         your-id
  medium:           your-id
  tumblr:           your-id
  email:            me@obartman.nl

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               ""

# URL
url:                "https://oscar-bartman.github.io"

baseurl:            "/Website"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Europe/London
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/oscar-bartman"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
